
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 110
lines = 35

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
import = ["/home/seven/.config/alacritty/colors.toml", "/home/seven/.config/alacritty/fonts.toml"]
